/// Flutter icons UPizza
/// Copyright (C) 2022 by original authors @ fluttericon.com, fontello.com
/// This font was generated by FlutterIcon.com, which is derived from Fontello.
///
/// To use this font, place it in your fonts/ directory and include the
/// following in your pubspec.yaml
///
/// flutter:
///   fonts:
///    - family:  UPizza
///      fonts:
///       - asset: fonts/UPizza.ttf
///
///
/// * Web Symbols, Copyright (c) 2011 by Just Be Nice studio. All rights reserved.
///         Author:    Just Be Nice studio
///         License:   SIL (http://scripts.sil.org/OFL)
///         Homepage:  http://www.justbenicestudio.com/
///
import 'package:flutter/material.dart';
import 'package:flutter/widgets.dart';
import 'package:flutter_svg/svg.dart';

class UPizzaIcons {
  UPizzaIcons._();

  static const _kFontFam = 'UPizzaIcons';
  static const String? _kFontPkg = null;

  // ignore: constant_identifier_names
  static const IconData right_circle =
      IconData(0xe800, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  // ignore: constant_identifier_names
  static const IconData left_circle =
      IconData(0xe801, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  // ignore: constant_identifier_names
  static const IconData down_circle =
      IconData(0xe802, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  // ignore: constant_identifier_names
  static const IconData up_circle =
      IconData(0xe803, fontFamily: _kFontFam, fontPackage: _kFontPkg);

  static Widget menuOpen({Color? color, double? width, double? height}) {
    return SvgPicture.asset(
      'assets/icons/menu_open_upizzas.svg',
      color: color,
      width: width,
      height: height,
    );
  }

  static Widget location({Color? color, double? width, double? height}) {
    return SvgPicture.asset(
      'assets/icons/location_upizzas.svg',
      color: color,
      width: width,
      height: height,
    );
  }

  static Widget cash({Color? color, double? width, double? height}) {
    return SvgPicture.asset(
      'assets/icons/cash.svg',
      color: color,
      width: width,
      height: height,
    );
  }

  static Widget creditCard({Color? color, double? width, double? height}) {
    return SvgPicture.asset(
      'assets/icons/credit_card.svg',
      color: color,
      width: width,
      height: height,
    );
  }

  static Widget pizzaPizza({Color? color, double? width, double? height}) {
    return SvgPicture.asset(
      'assets/icons/twemoji_pizzapizza.svg',
      color: color,
      width: width,
      height: height,
    );
  }

  static Widget cheeseFull({Color? color, double? width, double? height}) {
    return SvgPicture.asset(
      'assets/icons/cheese_full.svg',
      color: color,
      width: width,
      height: height,
    );
  }

  static Widget cheeseLeft({Color? color, double? width, double? height}) {
    return SvgPicture.asset(
      'assets/icons/cheese_left.svg',
      color: color,
      width: width,
      height: height,
    );
  }

  static Widget cheeseRight({Color? color, double? width, double? height}) {
    return SvgPicture.asset(
      'assets/icons/cheese_right.svg',
      color: color,
      width: width,
      height: height,
    );
  }
}
