name: u_pizzas
description: A new Flutter project.

publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: '>=2.18.5 <3.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  flutter_modular: ^5.0.3
  mobx: ^2.1.3
  flutter_mobx: ^2.0.6+5
  asuka: ^2.0.1+3
  dio: ^4.0.6
  flutter_screenutil: ^5.6.0
  firebase_core: ^2.4.0
  firebase_auth: ^4.2.0
  flutter_dotenv: ^5.0.2
  firebase_remote_config: ^3.0.7
  firebase_analytics: ^10.0.7
  logger: ^1.1.0
  shared_preferences: ^2.0.15
  flutter_secure_storage: ^7.0.0
  smooth_page_indicator: ^1.0.0+2
  flutter_svg: ^1.1.6
  carousel_slider: ^4.2.0
  tab_indicator_styler: ^2.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
  mobx_codegen: ^2.1.1
  build_runner: ^2.3.2


flutter:
  uses-material-design: true

  assets:
    - assets/images/
    - assets/icons/
    - .env
  #   - images/a_dot_ham.jpeg
  # example:
  fonts:
    - family: UPizzaIcons
      fonts:
        - asset: assets/fonts/UPizza.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
    - family: Inter
      fonts:
        - asset:  assets/fonts/inter/InterRegular.otf
        - asset:  assets/fonts/inter/InterBold.otf
          weight: 700
    - family: Montserrat
      fonts:
        - asset:  assets/fonts/montserrat/MontserratRegular.ttf
        - asset:  assets/fonts/montserrat/MontserratBold.ttf
          weight: 700
